### ISSUE TITLE
cant show maps

### ISSUE THREAD

**Issue by Faresapn** [rizmaulana/kotlin-mvvm-covid19#34]
in feature data in maps . the maps cant show data covid19 . 
![WhatsApp Image 2020-03-18 at 09 37 58](https://user-images.githubusercontent.com/39661274/76920027-0d74e280-68fd-11ea-812f-ff4c91cb4c27.jpeg)

**Comment by fajarnuha** [comment]
are you building on your own? you need Maps API key for that, at the moment we are not exposing the key to public

**Comment by Faresapn** [comment]
Thanks you

Pada tanggal Rab, 18 Mar 2020 11:48, Fajar Ulin Nuha <
notifications@github.com> menulis:
