### ISSUE TITLE
Impelement Indonesia details API

### ISSUE THREAD

**Issue by fajarnuha** [rizmaulana/kotlin-mvvm-covid19#38]
we will provide information about Indonesia data from this api `https://indonesia-covid-19-api.now.sh/api`. there are basically 2 options here:
1. Transform the API and combine it with existing API
2. Create another Country Detail Page that has more information about the country, in case of Indonesia, we can make it special by fetching data from the API and provides more insight, this can be the continuation from issue #18 

I think as the data has a lot of differences with the existing API, option 2 is more viable with more effort

**Comment by rizmaulana** [comment]
What about create new entry point? like `Country Detail` for now it's only indonesia, but we can add another for next.

**Comment by fajarnuha** [comment]
yes, that's like second option, where do you want to put the entry point?

**Comment by rizmaulana** [comment]
I will try to implement this
