### ISSUE TITLE
Can't build - no firebase package name found

### ISSUE THREAD

**Issue by ndom91** [rizmaulana/kotlin-mvvm-covid19#4]
So I wanted to go ahead and build this for myself, entered my own Google Maps API key, but then it still doesn't want to build.

Error message:
```
* What went wrong:
Execution failed for task ':app:processDevDebugGoogleServices'.
> No matching client found for package name 'id.rizmaulana.covid19.dev'
```

Should we setup our own firebase project for this as well?

Thanks for your work!

**Comment by rizmaulana** [comment]
You have to change build flavour into `prod`, don't use `dev` flavour because firebase keys is not provided for `dev` build.

**Comment by ndom91** [comment]
Ah that makes sense. Sorry more of a web guy than android ;)
