### ISSUE TITLE
Replace google maps with mapbox or open maps 

### ISSUE THREAD

**Issue by sagar-18** [rizmaulana/kotlin-mvvm-covid19#41]
Replace google maps with mapbox or open maps

**Comment by rizmaulana** [comment]
For what reason @sagar-18 ?

**Comment by sagar-18** [comment]
becoz google maps APIs are paid

**Comment by fajarnuha** [comment]
I think not if we are just showing static map, maybe what you meant is Place API

**Comment by rizmaulana** [comment]
Yes, mas @fajarnuha is right, it is free for mobile static maps
![image](https://user-images.githubusercontent.com/7193675/77244162-ca8c7500-6c44-11ea-9bd4-a148c4456484.png)
