### ISSUE TITLE
Error Build

### ISSUE THREAD

**Issue by arielcavadia1** [rizmaulana/kotlin-mvvm-covid19#46]
compile error says the manifest is not found. any solution?

**Comment by pandubaraja** [comment]
Hi @arielcavadia1, have you changed the value of `<GOOGLE_MAPS_API_KEY>` with your key in the `AndroidManifest.xml`?

<img width="480" alt="Screen Shot 2020-03-28 at 19 56 26" src="https://user-images.githubusercontent.com/30037407/77823518-54997980-712e-11ea-9619-d2566768bdfb.png">

**Comment by arielcavadia1** [comment]
Hello fellow, I have realized that I had to put the key of g maps, thanks for the help and burn work.
