### ISSUE TITLE
cant see graph for country

### ISSUE THREAD

**Issue by jfkdcman** [rizmaulana/kotlin-mvvm-covid19#51]
how do i access graph??

Also why some countries have negeative figures in recorded deaths

**Comment by fajarnuha** [comment]
you can access graph in this section
![Screenshot 2020-03-31 00 16 15](https://user-images.githubusercontent.com/15099703/77941795-e9de6e80-72e4-11ea-9ac8-14594e7f6113.png)

**Comment by fajarnuha** [comment]
and the negative value will be fixed very soon

**Comment by jfkdcman** [comment]
thanks for the help... you can delete this issue now since youve solved
it.. so that i the number of issues here reduces..''thank you

**Comment by jfkdcman** [comment]
Sir can i contract you to build the following for me??  How much will you
charge me?

I can provide you with the Instagram clone. And I need these following
features.. how much will you charge?

1. When user is posting video, give him option of selecting "Public" or
"Private".. Where Public Means the post will be accessible to everybody
even if someone is not following him. (Like how the app currently is).....
And "Private" will mean you will have to follow the person before the
private video will become visibile to his followers on TL or profile that
private post of the user for you to play and watch..

2. Create a points system where all users pay money through google pay in
order to get points..

3. Each user will have a chance to choose how many points he wants to
charge other users who want to follow him and gain access to all his
private contents as explained in point 1 above..

So that if i want to follow you and your charge is "100points", i will need
to have 100 points in my account first in order for me to be able to follow
you and access your content.. And the users who got followed will also have
that 100 points added to his account.. So he will have +100 points




4. When you follow someone, at the end of every 30 days, the same amount of
points will be deducted from your points bank in order for you to continue
being his follower.. If your available points is less than what the person
charges for followers, then you will automatically be made to unfollow
him.. (I guess this particular feature can be done with a cron job that
works on server side API or something)

**Comment by jfkdcman** [comment]
How do I change the country province daily stats to from Indonesia to my
own country???
