### ISSUE TITLE
VisualMaps Design Issue

### ISSUE THREAD

**Issue by fajarnuha** [rizmaulana/kotlin-mvvm-covid19#7]
Now map fragment needs to be initialized every time data changed from DetailViewModel, this causes problem such as
1. clutter issue, caused by 2x changing data causing double map fragment initialization
2. flexibility on handling changing data

I propose map fragment also observe DetailViewModel and DetailActivity just need to initialize the map fragment once

**Comment by rizmaulana** [comment]
Agree mas @fajarnuha I also realize that glitch, will soon create PR to fix them.
