### ISSUE TITLE
Sliding Panel Not Scrolling When Expanded

### ISSUE THREAD

**Issue by fajarnuha** [rizmaulana/kotlin-mvvm-covid19#9]
in Maps, sliding panel is not scrolling when expanded

**Comment by pandubaraja** [comment]
Investigating 🕵

**Comment by pandubaraja** [comment]
It seems the `SlidingUpPanelLayout` has a bug, if you set `app:umanoPanelHeight` to greater that 320dp for example 1000dp we can scroll it but the layout got scrambled.

How about we use `bottom_sheet_behaviour` from Android default instead @rizmaulana @isfaaghyth @fajarnuha ?

refs: 
- https://medium.com/android-bits/android-bottom-sheet-30284293f066
- https://stackoverflow.com/questions/51617186/bottomsheetbehavior-not-in-androidx-libraries

I've already try it and it works, I will make a PR when it is done so you guys can try it.

**Comment by fajarnuha** [comment]
i absolutely agree on this, lets use bottom_sheet_behaviour

**Comment by pandubaraja** [comment]
Please check on this PR https://github.com/rizmaulana/kotlin-mvvm-covid19/pull/14
